# Generated by Django 4.0.2 on 2025-05-11 22:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def crear_roles_iniciales(apps, schema_editor):
    # Obtenemos el modelo Rol desde las apps históricas
    Rol = apps.get_model('usuarios', 'Rol')
    
    # Creamos los roles predefinidos
    Rol.objects.create(
        nombre='postulante',
        descripcion='Usuario que busca empleo y puede postularse a ofertas de trabajo'
    )
    
    Rol.objects.create(
        nombre='empresa',
        descripcion='Usuario que representa a una empresa y puede publicar ofertas de trabajo'
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('clave', models.CharField(max_length=255)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('roles', models.ManyToManyField(to='usuarios.Rol')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Postulante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curriculum', models.TextField(blank=True, null=True)),
                ('experiencia_laboral', models.TextField(blank=True, null=True)),
                ('educacion', models.TextField(blank=True, null=True)),
                ('habilidades', models.TextField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulante', to='usuarios.usuario')),
            ],
            options={
                'db_table': 'postulantes',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=100)),
                ('sector', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('sitio_web', models.URLField(blank=True, max_length=100, null=True)),
                ('telefono_contacto', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresa', to='usuarios.usuario')),
            ],
            options={
                'db_table': 'empresa',
            },
        ),
        # Añadir esta operación al final para crear los roles después de que el modelo exista
        migrations.RunPython(crear_roles_iniciales),
    ]
