# Generated by Django 4.0.2 on 2025-05-11 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='empresa',
            table='empresas',
        ),
    ]
