# Generated by Django 4.0.2 on 2025-06-04 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_empresa_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulante',
            name='curriculum',
            field=models.FileField(blank=True, null=True, upload_to='curriculums/'),
        ),
    ]
