# Generated by Django 4.0.2 on 2025-05-12 17:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0002_alter_empresa_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('requisitos', models.TextField(blank=True, null=True, verbose_name='Requisitos')),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ubicación')),
                ('tipo_contrato', models.CharField(blank=True, choices=[('tiempo_completo', 'Tiempo Completo'), ('medio_tiempo', 'Medio Tiempo'), ('temporal', 'Temporal'), ('freelance', 'Freelance'), ('practicas', 'Prácticas/Pasantía'), ('proyecto', 'Por Proyecto')], max_length=50, null=True, verbose_name='Tipo de Contrato')),
                ('fecha_publicacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Publicación')),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('cerrada', 'Cerrada'), ('pausada', 'Pausada'), ('eliminada', 'Eliminada')], default='activa', max_length=20, verbose_name='Estado')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='usuarios.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Oferta de Empleo',
                'verbose_name_plural': 'Ofertas de Empleo',
                'db_table': 'oferta',
                'ordering': ['-fecha_publicacion'],
            },
        ),
    ]
