# Generated by Django 4.0.2 on 2025-05-12 17:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ofertas', '0001_initial'),
        ('usuarios', '0002_alter_empresa_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_postulacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Postulación')),
                ('estado', models.CharField(choices=[('enviada', 'Enviada'), ('en_revision', 'En revisión'), ('entrevista', 'Entrevista programada'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='enviada', max_length=20, verbose_name='Estado')),
                ('mensaje', models.TextField(blank=True, null=True, verbose_name='Mensaje de presentación')),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='ofertas.oferta', verbose_name='Oferta')),
                ('postulante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='usuarios.postulante', verbose_name='Postulante')),
            ],
            options={
                'verbose_name': 'Postulación',
                'verbose_name_plural': 'Postulaciones',
                'db_table': 'postulacion',
                'ordering': ['-fecha_postulacion'],
                'unique_together': {('oferta', 'postulante')},
            },
        ),
    ]
