# Generated by Django 4.0.2 on 2025-05-12 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postulaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='postulacion',
            table='postulaciones',
        ),
    ]
